#!/bin/bash

stat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages > /dev/null || exit 1

nr=$(cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages)
if [[ "$nr" == "4" ]]; then
    exit 0
else
    exit 1
fi
